Add foregroundServiceType="location" to NavigationNotificationService to prevent crash when starting notification.
java.lang.RuntimeException: Unable to start service androidx.car.app.sample.showcase.common.screens.navigationdemos.NavigationNotificationService@6ab3ba0 with Intent { xflg=0x4 cmp=androidx.car.app.sample.showcase/.common.screens.navigationdemos.NavigationNotificationService } Caused by: java.lang.IllegalArgumentException: foregroundServiceType 0x00000008 is not a subset of foregroundServiceType attribute 0x00000000 in service element of manifest file

Bug: 494690704
Fix: 494690704
Change-Id: I4014ea7e4a9debaec958a18eddbda3965560b2c6